name: test_env
channels:
- conda-forge
dependencies:
# We pin freetype and matplotlib for the image comparison
- freetype=2.10
- matplotlib-base=3.5.1
- pytest
- pytest-mpl
# Regression introduced in https://github.com/pytest-dev/pytest-xdist/pull/778
- pytest-xdist <3.5
- pytest-rerunfailures
- pytest-instafail
- pooch
- setuptools-scm
