name: 'Nightly Merge'

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  nightly-merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@f9e5f76d2c4e3fbfa5d44c6ee414b46b336df504
      with:
        stable_branch: 'RELEASE_next_patch'
        development_branch: 'RELEASE_next_minor'
        allow_ff: true
        allow_forks: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
